=== Rukesh2274/Xml_Learning/XMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/NewXMLSchema" xmlns:tns="http://www.example.org/NewXMLSchema" elementFormDefault="qualified">
 <xs:element name="book">
	<xs:complexType>
		<xs:sequence>
 <xs:element name="book" maxOccurs="unbounded">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="title" type="xs:string" maxOccurs="1"></xs:element>
			<xs:element name="authors" type="xs:string" maxOccurs="4"></xs:element>
			<xs:element name="price" type="xs:decimal" maxOccurs="1"></xs:element>
			<xs:element name="quantity" type="xs:string" maxOccurs="1"></xs:element>
		</xs:sequence>
			<xs:attribute name="Bid" type="xs:int"></xs:attribute>
	</xs:complexType>
 </xs:element>
 </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>

=== Rukesh2274/Xml_Learning/book.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="BookStyle.xsl"?>
<xs:book xmlns:xs="http://www.example.org/NewXMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/NewXMLSchema XMLSchema.xsd ">
  <xs:book>
    <xs:title>xs:Cricket</xs:title>
    <xs:authors>xs:Rukesh</xs:authors>
    <xs:price>100000.1</xs:price>
    <xs:quantity>xs:20</xs:quantity>
  </xs:book>
  
  <xs:book>
    <xs:title>xs:Cricket-Gully</xs:title>
    <xs:authors>xs:Rukesh1</xs:authors>
    <xs:price>100001.1</xs:price>
    <xs:quantity>xs:21</xs:quantity>
  </xs:book>
  
  <xs:book>
    <xs:title>xs:Cricket-Test</xs:title>
    <xs:authors>xs:Rukesh2</xs:authors>
    <xs:price>100002.1</xs:price>
    <xs:quantity>xs:22</xs:quantity>
  </xs:book>
  
  <xs:book>
    <xs:title>xs:Cricket-Stadium</xs:title>
    <xs:authors>xs:Rukesh3</xs:authors>
    <xs:price>100003.1</xs:price>
    <xs:quantity>xs:23</xs:quantity>
  </xs:book>
  
  <xs:book>
    <xs:title>xs:Cricket_ODI</xs:title>
    <xs:authors>xs:Rukesh4</xs:authors>
    <xs:price>100004.1</xs:price>
    <xs:quantity>xs:24</xs:quantity>
  </xs:book>
</xs:book>
